---
title: "Heliconia Demography Project"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
# - \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{HDP Summary, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/
bibliography: references.bib
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


```{r data, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
# knitr::opts_chunk$set(echo = FALSE)
ha_plants <- read_csv("./data_clean/HDP_1997_2009.csv", col_types = cols())
ha_plots <- read_csv("./data_clean/HDP_plots.csv", col_types = cols())
ha_plants <- ha_plants %>% left_join(ha_plots)
```

# Heliconia Demography Project


```{r nplants, cached=TRUE, warning=FALSE,message = FALSE}
nplants<-ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N_plants = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N_plants)) %>%
  ungroup() %>%
  summarize(total_plants = sum(N_plants))

```


## Total Number of Plants: `r nplants`


## Plants per Plot

```{r nplants_total, cached=TRUE, warning=FALSE,message = FALSE}
nplants_total<-ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N_plants = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N_plants))
nplants_total
```
## Plants per Habitat Type

```{r n_by_habitat, cached=TRUE, warning=FALSE,message = FALSE}
n_by_habitat<-
ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N_plants = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N_plants)) %>%
  summarize(N_plants = sum(N_plants))
n_by_habitat
```


## Seedlings per plot

```{r sldgs, cached=TRUE, warning=FALSE,message = FALSE}
n_sdlgs<-
ha_plants %>%
  group_by(plot) %>%
  filter(recorded_sdlg == TRUE) %>%
  group_by(plot) %>%
  tally() %>%
  arrange(desc(n))
n_sdlgs
```

## Plants without Tags

```{r no_tag, cached=TRUE, warning=FALSE,message = FALSE}
no_tag<-
ha_plants %>%
  filter(found_without_tag == TRUE) %>%
  group_by(habitat, plot) %>%
  summarize(N_plants = n_distinct(plant_id))

no_tag
```

```{r recrt_yr, cached=TRUE, warning=FALSE,message = FALSE}
ha_recruit_yr <- ha_plants %>%
  group_by(plant_id) %>% 
  filter(census_status == "measured") %>%
  filter(row_number() == 1)
hist(ha_recruit_yr$year)
ha_recruit_yr %>%
  group_by(year) %>%
  count() %>%
  ungroup() %>%
  mutate(freq = (n / sum(n) * 100)) %>%
  mutate(cumulative_freq = (cumsum(n) / sum(n) * 100))
```


