---
title: |
    | *Ecology*: Data Paper 
    | Appendix S1 for _Demography of the understory herb_ Heliconia acuminata _(Heliconiaceae) in an experimentally fragmented tropical landscape_
shorttitle        : "Tropical plant demography"
author: 
  - name          : "Emilio M. Bruna"
    affiliation   : "1,2,3"
    address       : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
    email         : "embruna@ufl.edu"
    # corresponding : yes
  - name          : "Maria Uriarte"
    affiliation   : "4"
    
      
  - name          : "Maria Rosa Darrigo"
    affiliation   : "3"
    
    
  - name          : "Paulo Rubim"
    affiliation   : "3"
    
  - name          : "Cristiane F. Jurinitz"
    affiliation   : "3"
    
  - name          : "Eric R. Scott"
    affiliation   : "1"
  - name        : "W. John Kress"
    affiliation : "5"
affiliation:
  - id            : "1"
    institution   : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
  - id            : "2"
    institution   : "Center for Latin American Studies, University of Florida, PO Box 115530, Gainesville, FL 32611-5530, USA"
  - id            : "3"
    institution   : "Biological Dynamics of Forest Fragments Project, INPA-PDBFF, CP 478, Manaus, AM 69011-970, Brazil"
  - id            : "4"
    institution   : "Department of Ecology, Evolution and Environmental Biology, Columbia University, 1200 Amsterdam Ave., New York, New York 10027, USA"
  - id            : "5"
    institution   : "Department of Botany, National Museum of Natural History, PO Box 37012, Smithsonian Institution, PO Box 37012, Washington DC, USA"

authornote: |

  _Corresponding author_: Emilio M. Bruna (embruna@ufl.edu)
  
floatsintext      : no
figurelist        : yes
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
documentclass     : "apa6"
# classoption       : "man"
classoption       : "man, donotrepeattitle" # suppresses title on 1st page of MS
output: papaja::apa6_pdf
  # papaja::apa6_pdf:
#     latex_engine: xelatex
mainfont: Times New Roman
fontsize: 12pt
bibliography: ["references.bib"]
csl: ecology.csl
fig_caption: yes #yes will automatically add "Figure X" to the start 
always_allow_html: yes
header-includes:
  - \usepackage{booktabs}
  - \raggedbottom
  - \usepackage{tabu}
  - \usepackage{pdflscape}
  - \usepackage{longtable}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \setlength\parindent{22pt}
editor_options: 
  markdown: 
    wrap: 72
---

```{r GlobalOptions}
options(knitr.duplicate.label = 'allow')
```

```{r setup, include = FALSE}
# library("papaja")
# r_refs("APCpaper_QSS.bib")
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
library(knitr)
library(cowplot)
# library(egg)
# library(magick)
# library(citr)
# library(devtools)
# devtools::install_github("crsh/papaja")
```
<!-- renaming and renumbering SI: https://github.com/crsh/papaja/issues/259 -->
<!-- \appendix -->
<!-- \renewcommand{\appendixname}{Appendix S1} -->
\renewcommand{\thefigure}{S\arabic{figure}} \setcounter{figure}{0}

<!-- \renewcommand{\thetable}{SI\arabic{table}} \setcounter{table}{0} -->
<!-- \renewcommand{\theequation}{SI\arabic{table}} \setcounter{equation}{0} -->
# Appendix S1

The dimensions of the Heliconia Demographic Project (HDP) plots are $50\times100$m, and each plot is subdivided into 50 contiguous subplots of $10\times10$m to facilitate the surveys. Figures S1 and S2 show the orientation of each HDP plot and numbering of the subplots. 

<!-- \setcounter{page}{1} -->
```{r figs, out.width = "100%", fig.cap='Schematic of the location, orientation, and layout of each \\textit{Heliconia} Demographic Plots. The plots are located in Forest Fragments (A-G) or Continuous Forest (H-M).', echo=FALSE}


ff1 <- ggdraw() + draw_image('./Manuscript/figures/ff1.jpeg', scale = 1)
ff2 <- ggdraw() + draw_image('./Manuscript/figures/ff2.jpeg', scale = 1)
ff3 <- ggdraw() + draw_image('./Manuscript/figures/ff3.jpeg', scale = 1)
ff4 <- ggdraw() + draw_image('./Manuscript/figures/ff4.jpeg', scale = 1)
ff5 <- ggdraw() + draw_image('./Manuscript/figures/ff5.jpeg', scale = 1)
ff6 <- ggdraw() + draw_image('./Manuscript/figures/ff6.jpeg', scale = 1)
ff7 <- ggdraw() + draw_image('./Manuscript/figures/ff7.jpeg', scale = 1)


cf1<- ggdraw() + draw_image('./Manuscript/figures/cf1.jpeg', scale = 1)
cf2<- ggdraw() + draw_image('./Manuscript/figures/cf2.jpeg', scale = 1)
cf3<- ggdraw() + draw_image('./Manuscript/figures/cf3.jpeg', scale = 1)
cf4 <- ggdraw() + draw_image('./Manuscript/figures/cf4.jpeg')
cf5 <- ggdraw() + draw_image('./Manuscript/figures/cf5.jpeg')
cf6 <- ggdraw() + draw_image('./Manuscript/figures/cf6.jpeg', scale = 1)

```

```{r fig2, fig.cap='Schematic of the orientation and layout of the \\textit{Heliconia} Demographic Plots in forest fragments.',fig.height = 10, fig.width = 7, fig.align = "center"}
plot_grid(ff1,ff2,ff3,ff4,ff5,ff6,ff7,
          # labels = c('A', 'B', 'C','D','E', 'F', 'G'),
          ncol=2)
```

```{r fig3, fig.height = 8, fig.width = 5, fig.align = "center", fig.cap='Schematic of the orientation and layout of each \\textit{Heliconia} Demographic Plot in continuous forest.', fig.height = 10, fig.width = 7, fig.align = "center"}
plot_grid(cf1,cf2,cf3,cf4,cf5,cf6,
          # labels = c('A', 'B', 'C','D','E', 'F'),
          ncol=2)

```
