---
title: "Overview: Heliconia Survey Data" 
date: "last update: `r Sys.Date()`"
author: "Emilio M. Bruna"
output: rmdformats::robobook
# rmdformats::downcute:
    
self_contained: true
thumbnails: true
lightbox: true
gallery: false
highlight: tango
bookdown: true
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(kableExtra)
library(here)

knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```



```{r data, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
# here::here()
ha_plants <- read_csv(here("data","survey_clean","heliconia_survey_clean.csv"),
                      col_types = cols())

ha_plots <- read_csv(here("./data/survey_archive/HDP_plots.csv"), col_types = cols())
ha_plants <- ha_plants %>% left_join(ha_plots)
```

```{r nplants, cached=TRUE, warning=FALSE,message = FALSE}
nplants<-ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N_plants = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N_plants)) %>%
  ungroup() %>%
  summarize(total_plants = sum(N_plants))
```

---

## __Last update:__

`r Sys.Date()`

--- 

## __Total no. of plants:__ 

N = `r nplants`  

---

## __Plants x Habitat__

```{r n_by_habitat, cached=TRUE, warning=FALSE,message = FALSE}
n_by_habitat<-
ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N)) %>%
  summarize(N = sum(N)) %>% 
  arrange(N)
kbl(n_by_habitat)
```

---

## __Plants x Demographic Plot__

```{r nplants_total, cached=TRUE, warning=FALSE,message = FALSE}
nplants_total<-ha_plants %>%
  group_by(habitat, plot) %>%
  summarize(N = n_distinct(plant_id)) %>%
  arrange(habitat, desc(N))
kbl(nplants_total)
```

--- 

## __Seedlings x Demographic Plot__

```{r sldgs, cached=TRUE, warning=FALSE,message = FALSE}
n_sdlgs<-
ha_plants %>%
  filter(recorded_sdlg == TRUE) %>%
  group_by(habitat, plot) %>%
  tally() %>%
  arrange(habitat, desc(n))
kbl(n_sdlgs)
```
--- 

<!-- ## __Established plants found without tags during the surveys__ -->

<!-- ```{r no_tag, cached=TRUE, warning=FALSE,message = FALSE} -->
<!-- no_tag<-ha_plants %>% -->
<!--   filter(adult_no_tag == TRUE) %>% -->
<!--   group_by(habitat, plot) %>% -->
<!--   summarize(N = n_distinct(plant_id)) %>% -->
<!--   arrange(habitat, desc(N)) -->
<!-- kbl(no_tag) -->
<!-- ``` -->
<!-- --- -->

## __Plants x Year__

```{r recrt_yr, cached=TRUE, warning=FALSE,message = FALSE}
marked_per_yr <- ha_plants %>%
  group_by(plant_id) %>%
  filter(census_status == "measured") %>%
  filter(row_number() == 1) %>%
  group_by(year) %>%
  count() %>%
  ungroup() %>%
  mutate('%' = round((n / sum(n) * 100),1)) %>%
  mutate('cumulative %' = round((cumsum(n) / sum(n) * 100),1))
kbl(marked_per_yr)
```

---

# **Return to the HDP Github Repository:** [Link](https://github.com/BrunaLab/HeliconiaSurveys)

