---
title: "HDP Publications & Supplementary Data"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
- \fancyhead[R]{HDP Summary, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}

- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/
# bibliography: references.bib
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
bibliography: ["./HeliconiaSurveys_papers/HeliconiaSurveys_papers.bib","./HeliconiaSurveys_related/HeliconiaSurveys_related.bib","./HeliconiaSurveys_datasets/HeliconiaSurveys_datasets.bib" ]
csl: ecology.csl
output:
  rmdformats::robobook:
    # code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
  
    # output:
#   # pdf_document: default
#   # html_document:
#   #   df_print: paged
#   rmdformats::robobook: default
# editor_options: 
#   markdown: 
#     wrap: 72
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```







--- 
nocite: |
    
    @leiteModelingPersistencePlant2021; @brooksStatisticalModelingPatterns2019a, @brunaArePlantPopulations2003a, @brunaBiologicalImpactsDeforestation2004, @brunaCompensatoryResponsesUnderstory2005d, @brunaDemographicEffectsHabitat2005, @brunaEdgeEffectsGrowth2011c, @brunaEffectsForestFragmentation2002b, @brunaExperimentalAssessmentHeliconia2002, @brunaForestFragmentsTropical2005, @brunaHabitatFragmentationDemographic2002b, @brunaHeliconiaAcuminataReproductive2004e, @brunaRegenerationPopulationStructure2005d, @brunaSeedGerminationRainforest1999b, @cortesCharacterization10Microsatellite2009c, @cortesLowPlantDensity2013b, @fiskeAlternativeSpatialSampling2010, @fiskeEffectsSampleSize2008a, @gagnonGrowthUnderstoryHerb2011b, @morrisLongevityCanBuffer2008a, @ribeiroInfluencePostClearingTreatment2010b, @scottDelayedEffectsClimate2021, @uriarteDisentanglingDriversReduced2011b, @uriarteEffectsForestFragmentation2010b
---   



### Other HDP Datasets

1. Bruna, Emilio M. (2014): *Heliconia acuminata* seed set (seeds per fruit) 2008. figshare. Dataset. [https://doi.org/10.6084/m9.figshare.1273926.v2](https://doi.org/10.6084/m9.figshare.1273926.v2) 

1. Bruna, Emilio M. (2014): Map of BDFFP Reserve 1501, Manaus, Brazil. figshare. Dataset. [https://doi.org/10.6084/m9.figshare.1157869.v1](https://doi.org/10.6084/m9.figshare.1157869.v1) 

1. Bruna, Emilio M. (2012): _Heliconia acuminata_ (Heliconiaceae) Leaf Length vs. Leaf Area. figshare. Dataset. [(https://doi.org/10.6084/m9.figshare.92691 )](https://doi.org/10.6084/m9.figshare.92691)

1. *Heliconia acuminata* microsatellite markers from [Côrtes et al. 2009](https://doi.org/10.1111/j.1755-0998.2009.02627.x), *Molecular Ecology Resources*: [[Genbank Archive]](https://www.ncbi.nlm.nih.gov/nuccore/?term=heliconia%20acuminata%20bruna) 


    **For a *.bib* file of these datasets [[click here]](https://github.com/BrunaLab/HeliconiaSurveys/blob/a2d8dcc79119efcefc196e0fd5138e878e0cca24/docs/HeliconiaSurveys_datasets/HeliconiaSurveys_datasets.bib).**

---

#### HDP Articles and Book Chapters

 **For a *.bib* file of these references [[click here]](https://github.com/BrunaLab/HeliconiaSurveys/blob/1649ea958df1fc2da0187693bca40ce38bebb759/docs/HeliconiaSurveys_papers/HeliconiaSurveys_papers.bib).**


