---
title: " "

csl: ecology.csl
bibliography: ["./HeliconiaSurveys_papers/HeliconiaSurveys_papers.bib","./HeliconiaSurveys_related/HeliconiaSurveys_related.bib","./HeliconiaSurveys_datasets/HeliconiaSurveys_datasets.bib" ]
output: 
  rmdformats::robobook
#   # rmdformats::downcute:
    
self_contained: true
thumbnails: true
lightbox: true
gallery: false
highlight: tango
bookdown: true
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)


```


nocite: |
    
    @leiteModelingPersistencePlant2021; @brooksStatisticalModelingPatterns2019a, @brunaArePlantPopulations2003a, @brunaBiologicalImpactsDeforestation2004, @brunaCompensatoryResponsesUnderstory2005d, @brunaDemographicEffectsHabitat2005, @brunaEdgeEffectsGrowth2011c, @brunaEffectsForestFragmentation2002b, @brunaExperimentalAssessmentHeliconia2002, @brunaForestFragmentsTropical2005, @brunaHabitatFragmentationDemographic2002b, @brunaHeliconiaAcuminataReproductive2004e, @brunaRegenerationPopulationStructure2005d, @brunaSeedGerminationRainforest1999b, @cortesCharacterization10Microsatellite2009c, @cortesLowPlantDensity2013b, @fiskeAlternativeSpatialSampling2010, @fiskeEffectsSampleSize2008a, @gagnonGrowthUnderstoryHerb2011b, @morrisLongevityCanBuffer2008a, @ribeiroInfluencePostClearingTreatment2010b, @scottDelayedEffectsClimate2021, @uriarteDisentanglingDriversReduced2011b, @uriarteEffectsForestFragmentation2010b
---   


# HDP Publications

 **For a *.bib* file of these references [[click here]](https://github.com/BrunaLab/HeliconiaSurveys/blob/1649ea958df1fc2da0187693bca40ce38bebb759/docs/HeliconiaSurveys_papers/HeliconiaSurveys_papers.bib).**


---

