---
title: "Tag Change Records"
date: "updated: `r Sys.Date()`"
# layout: page
# permalink: HeliconiaSurveys/TagChanges
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
- \fancyhead[R]{HDP Tag Changes, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}

- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/
# bibliography: references.bib
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  # pdf_document: default
  # html_document:
  #   df_print: paged
  rmdformats::robobook: default
# editor_options: 
#   markdown: 
#     wrap: 72
---



```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r data, cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
tag_changes <- read_csv("./data/data_raw/tag_changes.csv", col_types = cols())
ha_sites <- read_csv("./data/data_clean/heliconia_data_clean.csv", col_types = cols()) %>% 
  select(habitat,plot_id,plot,bdffp_reserve_no,ranch) %>% 
  unique()
tag_changes<-left_join(tag_changes,ha_sites, by="plot") %>% 
  select(habitat,ranch,plot_id,plot,year,old_tag_no,new_tag_number,notes)
rm(ha_sites)
  
# ANY CHANGES TO THE TAG NUMBERS AS OF June 1, 2023 WILL BE ENTERED HERE

tag_changes_updated <- tag_changes
# %>% 

write_csv(tag_changes_updated, "./data/data_clean/tag_changes.csv")
```


## Tag Number Changes

**Last update:** `r format(Sys.time(), '%d %B %Y')`

Field survey teams periodically change the tags attached to individual plants (e.g., if the tag becomes difficult to read or the tag is lost). Below is a record of these changes; these records are necessary when using the original data sheets to validate plant records.    

```{r nplants_total, cached=TRUE, warning=FALSE,message = FALSE}

tag_changes_updated<-tag_changes_updated %>%
  group_by(plot) %>%
  arrange(plot, year)
kbl(tag_changes_updated)
```


